name: FloatingTextCreator
author: Vecnavium
description: A PocketMine-MP FloatingTextCreator completely different from the others on Poggit.
api: 4.0.0
version: 2.0.0
main: Vecnavium\FloatingTextCreator\Main
mcpe-protocol: [465]

permissions:
    ftc.command:
      default: op
      description: "Permission and the ability to see IDs and manage FloatingTexts"
