#==========================================#
#Config File for FloatingTextCreator
#==========================================#

CONFIG_VERSION: 1

# Time in seconds for all FloatingTxts to refresh (seconds)
ft-updatetime: 1

# Supported tags for the plugin

# {line} or \n -  Adds an additional line on the text
# {player} - Get the player's username
# {ip} - Get the server's IP
# {port} - Get the server's Port
# {ping} - Get the player's ping
# {world} - Get the world the user is in.

# You can create as much as you want, simply follow the pattern to avoid any errors.
ft-texts:
  WelcomeText:
    - "Hello {player} welcome to the server!"
  RandomText:
    - "Hello world! 1"
    - "Hello world! 2"

